#%RAML 1.0 NamedExample
value:

    "source_location": "Bath"
    "destination_location": "london"
    "from_time": "10:30:00"
    "to_time": "11:00:00"
    "Advance_notify_time_min": "30:00:00"
    
